### ISSUE TITLE
Current energy is showing as KW not Watts

### ISSUE THREAD

**Issue by OneScuzzie2k** [petretiandrea/home-assistant-tapo-p100#202]
The current energy is showing as KWs not Watts, how can I change this?

**Comment by jjdiazgarcia** [comment]
I think it is fine to show it in kw as it shows the sum of all days consumption.

Anyway, it is defined in file https://github.com/petretiandrea/home-assistant-tapo-p100/blob/main/custom_components/tapo/tapo_sensor_entity.py using variable ENERGY_KILO_WATT_HOUR.
You should be able to change it by another variable that set watts instead of kW

KR
