### ISSUE TITLE
Device is already configured

### ISSUE THREAD

**Issue by ChoppyThing** [petretiandrea/home-assistant-tapo-p100#213]
Hello,

I got an issue lately where my switches (p100) where no longer available. They were grayed out on home assistant but still working on the official tapo application.
So i thought about deleting the integrations before adding them again.
I deleted them one by one and tried adding a device again, but i get this message : Device is already configured

I wonder where are the config files where this is declared so i can delete them from the source.

I also wonder if the solution is not to remove the tapo integration completely and install it again ? How should i do that ?

Thanks for your help

**Comment by psampatakos** [comment]
I have the exact same issue. I have two p100 smart plugs and although they both work through the tapo app only one can be added to HA. When I try to add the second one a message "the device already exists" appears.

Any help would be appreciated 
Thanks

**Comment by petretiandrea** [comment]
"the device already exists" is issued when there is two devices with same MAC address, please check that you adding the right devices. Additionally, check the configuration.yml and be sure there is not the same device that are you trying to add with UI or viceversa.

**Comment by psampatakos** [comment]
My router correctly depicts that the two smart plugs (with different MAC addresses) have different IPs. My cinfiguration.yaml is empty . Where is the information of the added devices kept so I can check against which device the integration checks the one I am trying to add?

**Comment by HumanSkunk** [comment]
@psampatakos @ChoppyThing I know this has been a while but did you ever manage to resolve this? I have the same issue and I was just about to open another ticket when I noticed this one was names almost identically. I had an old plug previously monitoring Elec usage for my Fridge. I have since moved it to the lounge for the TV but in the meantime it hadn't been used for several months so I removed it from the Tapo Integration as it was constantly trying to poll it and it was never connected.

When I am trying to add the device now I get the "device already configured" message. I have tried giving it a different IP but as above it appears it uses its MAC address. There is nothing else added to my router with that MAC, there is also nothing manually configured with yaml as it was all done with the GUI.

I have looked through the custom components directory but there doesnt seem anything obvious to delete. I have reused plugs and gave them new names which has required adding them again to function properly but never had this error before.
