### ISSUE TITLE
Hub needed

### ISSUE THREAD

**Issue by arkpoah** [petretiandrea/home-assistant-tapo-p100#337]
I recently added the L900 light strip device successfully, then I bought a new Tapo device not yet supported here : T110 contact sensor.
When I tried to add it in Tapo application, it refuses can the H100 hub is needed.

Is there a way to support this device without the hub ?

Thanks

**Comment by seba1337** [comment]
No. The sensors don't use WiFi but a proprietary protocol that runs on ~900 MHz, that's why they need the hub. The H100 hub also isn't reverse engineered. I do have the H100 hub, the L900 light strip and the T110 contact sensor and they do work nicely together with the Tapo app, but that's about it.

See https://github.com/petretiandrea/home-assistant-tapo-p100/issues/354
