### ISSUE TITLE
L630 bright issue

### ISSUE THREAD

**Issue by simonetrob** [petretiandrea/home-assistant-tapo-p100#372]
hello,  this integration works properly, but when i call a scene with a specific bright level, this lamp remain with past brightness, someone else had this problem?

**Comment by Brevhead** [comment]
I have had issues with scenes not working on Tapo lights through this since a recent update, but I found the problem to be related to the Default State setting in the Tapo app itself.  If this was set to custom, it would override my scene selection.  I amended it to Last 'On' State and it seems to have fixed the problem.  I guess the way in which the scene is called, it must go off and on again or something and trigger the custom Default State that overrides the scene.  Its a bit annoying as it was working ok previously, and I preferred to have a custom Default State as the wife and kids don't like to mess about with the brightness much.
