### ISSUE TITLE
Support for S200B switch?

### ISSUE THREAD

**Issue by gurufordy** [petretiandrea/home-assistant-tapo-p100#376]
Not sure how new this device is, but has anyone confirmed if it can be used? If not, it would be awesome to be able to use this switch with HASS!

https://www.tp-link.com/uk/home-networking/smart-switch/tapo-s200b/

**Comment by jasoares** [comment]
I was looking for the same thing but since I didn't see any of the devices that require the Tapo Hub H100 being supported I wasn't even going to ask.
I personally own both the button S200B and the humidity/temperature sensor T310 along the hub obviously, I can try to understand how tricky it is to add support for these devices that need a gateway. 
Since it would be my first time developing an integration like this, would anyone have any idea of how difficult it is (or even possible) to access these devices through the gateway? @petretiandrea any pointers?

**Comment by TheWhiteWarlock** [comment]
Same, need HA integration with my T310's and T315's

**Comment by TeDeVPrime** [comment]
any news here for this switch?

**Comment by petretiandrea** [comment]
Refers to #354

**Comment by Dan-Sun** [comment]
I think it could be reopened again since this device isn't really supported/usable.

You mentioned it why https://github.com/petretiandrea/home-assistant-tapo-p100/issues/354#issuecomment-1706967148 but it keeps the search in a circle. This issue is better to be open.
