### ISSUE TITLE
Can't setup tapo controller from home assistant integration list in UI

### ISSUE THREAD

**Issue by Marc1200** [petretiandrea/home-assistant-tapo-p100#401]
Hello,
I cannot setup tapo controller from home assistant ui, it keeps loading and then it gives this error message:

It says: error cannot load config-flow

![Screenshot_20230407-151952~2](https://user-images.githubusercontent.com/68737063/230616083-8c1f3419-60b3-47cc-9c1a-1b413171d568.png)
![Screenshot_20230407-152055~2](https://user-images.githubusercontent.com/68737063/230616096-bd1a4424-f750-4603-8a26-d2dae76d246c.png)

**Comment by mobcdi** [comment]
No Tapo integration listed for HA 2023.6.1

**Comment by bartlomiejwulff** [comment]
Same here!

**Comment by mobcdi** [comment]
@bartlomiejwulff have you installed the HACS integration in order to be able to search that for the Tapo integration there? I was confused when I tried installation first because I was thinking of the integrations offered by home assistant not the Home assistant Community Store (HACS) www.hacs.xyz . When you have HACS installed you will see a new menu option and from there will be able to install tapo integration

**Comment by bartlomiejwulff** [comment]
> @bartlomiejwulff have you installed the HACS integration in order to be able to search that for the Tapo integration there? I was confused when I tried installation first because I was thinking of the integrations offered by home assistant not the Home assistant Community Store (HACS) [www.hacs.xyz](http://www.hacs.xyz) . When you have HACS installed you will see a new menu option and from there will be able to install tapo integration

I have installed this integration manually by copying the content of custom_components to my HA. The integration was found but the configuration UI ist loading infinitely.

**Comment by codyc1515** [comment]
I face this same issue now and again. Typically restarting HA fixes it. There is nothing in the typical logging level available to suggest why this happens.
