### ISSUE TITLE
All P1XX devices are disconnected, and can not be re-added

### ISSUE THREAD

**Issue by frank777777** [petretiandrea/home-assistant-tapo-p100#472]
## Version of the integration
V. 2.5.0
Account name (email)  all lowercase.

## Configuration
Tapo App - 
Versione 2.17.201 

devices:
1 for example 
P110
Hardawe version 1.0
firmware:
1.2.3 Build 2300425 Rel. 142542

```yaml
not sure which log I have to add here 
```

## Describe the bug
As an image describe more than 1000 words: 
( but in short, all my tapo  devices: P100;P110 etc, are in configuration failed , )

![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/110597948/245fd27a-b5ad-439a-8094-8a8d228ccb2b)

I do also tried to delete and  add again a device. ( it say it si not recognized  I tested password 3 times, ) 

## Debug log

Logger: homeassistant.config_entries
Source: config_entries.py:1250
First occurred: 11:02:04 (2 occurrences)
Last logged: 11:02:08

Config entry 'lavatrice' for tapo integration not ready yet: Returned error_code: TapoError.ERR_SESSION_TIMEOUT: Session Timeout; Retrying in background
Config entry 'piano cottura ' for tapo integration not ready yet: Returned error_code: TapoError.ERR_SESSION_TIMEOUT: Session Timeout; Retrying in background

```

**Comment by petretiandrea** [comment]
Are you controlling these devices from other sources? (like other integration, or application or something similar)

**Comment by frank777777** [comment]
I do sir, I do control this devices even via official Tapo App indeed, and to be sure I've deactivated the 2FA ( even if it was working smooth a week ago) ..

**Comment by frank777777** [comment]
and If could help, 
removing a device and trying to add it again, with Tapo App.  double checking on Paasword . and username lowercase 

![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/110597948/867a6ce7-9f6e-47cf-a744-77b4748ef2b4)

**Comment by guilhermeLSantos** [comment]
This happens constantly to me, one temporary solution, is to remove them from the Tapo app and reconfigure them all over again from Tapo App and then add them in Home Assistant.

But even then this solution isn't great because after some time, they all become like the following image:

![Captura de ecrã 2023-08-15 022215](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/50839004/68e185ba-ef45-4803-9e1b-d479a30f7278)

If you really really need them in Home Assistant, this is one way, but it's super clunky and bothersome to do this.
There seems to be a problem with keeping the devices connected to Home Assistant.
Maybe it has something do to with some kind of token being refreshed? I don't know.

**Comment by frank777777** [comment]
well. I removed it from the Tapo App -- then re-paired with tapo app, and then are back on the Home assistant . (have to check if automation and energy data remain. I presume I have to rewrite automation , and  no energy data ) .. I'll check  then ill write here    SO for now it works ( the old cancel and reinstall) ..

**Comment by petretiandrea** [comment]
#481 and version 2.6.1 should fix timeout session issue
