### ISSUE TITLE
Connection to a different wifi

### ISSUE THREAD

**Issue by Danimarch** [petretiandrea/home-assistant-tapo-p100#473]
Goodmorning,
I have installed Homeassistant on the pc and it is connected to home wifi, when tapo is connected to the same home assistant network i have no problem, but if tapo has a different wifi than Homeassistant he won't connect. This problem arises because I would like to manage my smart sockets located in another house with only one home assistant. 
How can i fix it?
Thank you all
and have a good day

**Comment by petretiandrea** [comment]
This issue is out of scope and regard to your network configuration. The integration works on local area network avoiding using cloud services (this guarantee to work even no internet access working). So home assistant must "see" your tapo device, this constraints could be achieved in a different ways:
- homeassistant and tapo devices on same network
- homeassistant and your "second" house has a VPN-like connection which allows homeassistanto to ping your tapodevices
- install another homeassistant instance in your second house
