### ISSUE TITLE
P110 Month energy is showing Today energy once added to the Energy tab

### ISSUE THREAD

**Issue by scotrod** [petretiandrea/home-assistant-tapo-p100#518]
Version: v2.8.2
Env: Home Assistant 2023.9.2 Supervisor 2023.08.3 Operating System 10.5 Frontend 20230911.0 - latest

While looking at the telemetry in the device view, the data is correct:
![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/45900128/a0f2f5b0-d2d6-48ff-8c6e-ea312fdeabfb)

However, once I add the P110 Month and Today Energy in the Energy dashboard:
![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/45900128/aecfb1c0-93a6-4f61-8682-2c0bdc898714)

And I go to the Enrgy tab, both of the fields are equal, showing only Today's data:
![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/45900128/390dc06c-06d8-41b2-b727-dd09eeeee09f)

There is nothing in this form that shows how to collect logs from the integration for debugging. Please aid me on how to get em' so we can get more visibility.

Thank you.

**Comment by f-fritz** [comment]
That's expected behavior by HA. You could add an indefinitely increasing counter there that tracks the all time energy consumption of a hypothetical device. The energy dashboard will only look at the increment per day. I guess internally it works like a Device > Helper > Utility Meter that resets every 24h. If you want to inspect the monthly consumption, change the Energy Dashboard's resolution from "Day" to "Month" in the upper right corner. That will aggregate all daily measures into a monthly value.

**Comment by scotrod** [comment]
Thank you for the suggestion - Indeed, just getting the monthly data was the most straightforward solution. I just wanted to bring this up, because a few months ago the data for Month and Day energy was different and accurate. I don't look up this data regularly so I don't know whether HA or an add-on update might have broke this.
