### ISSUE TITLE
Tapo P125M not working on TC 2.12.0

### ISSUE THREAD

**Issue by jerry30678** [petretiandrea/home-assistant-tapo-p100#626]
Current HA Core ： 2023.11.3
Current Firmware：1.0.7 Build 230801 Rel.091142

I have attempted to remove and add the P125M device, and have also reinstalled TC 2.12.0.

TC version: v.2.11.0 ：work fine, I can control the switch on/off.
![2 11 0](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/152282942/fb19dfbd-79de-4c08-969a-466687ce0153)

---------------------------------------------------------------------------------------------------

TC version: v.2.12.0 ：I can't control it, and the current power, monthly energy, and daily energy readings are not working.
![2 12 0](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/152282942/f8ff92bf-003e-4efd-be67-17e023dfd654)

**Comment by Xarishark** [comment]
I lost all my light bulbs too and cant readd them. it just fails

**Comment by cfurini** [comment]
I am having the exact same problem. I have 3 P125M. After upgrading to TC 2.12.0 the switches stopped working. I decided to delete one device and add it again. After that, I noticed it came up with only 7 entities instead of 9 and the ON/OFF control was not there anymore. 

![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/62850180/103952ba-fa70-458d-a744-8c46697f4cde)

**Comment by cfurini** [comment]
Ok. I just restored HA Core to 2023.11.2 and my P125M are back working. Actually, each device has 4 entities being one of them the Control.

![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/62850180/ce6b86c7-daba-4e39-8459-731ee274b01f)

![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/62850180/b8d31408-cc11-4fc4-8af5-7dfd866eaa6a)
