### ISSUE TITLE
Releases 3.1.4

### ISSUE THREAD

**Issue by tuliuliucroman** [petretiandrea/home-assistant-tapo-p100#789]
Good afternoon. When installing version 3.1.4, the integration says 3.1.2 - is this an error? Devices connected to the H100 and KH100 gateways are not connected. When I try to install the working version 3.0.0, it is not in the list.
![16,07](https://github.com/user-attachments/assets/a2be4421-b945-433f-9f34-a0db1b030f98)
![16,07_1](https://github.com/user-attachments/assets/e246179c-250d-4ff8-954d-2093b802ab12)

**Comment by AndreasExner** [comment]
+1, same issues

**Comment by ThiSchmidt** [comment]
Yes it should be a bug, the version number in the constants ist not set to 3.1.4, but probably you are running 3.1.4.

Yes, it is still a problem that versions above 3.0.0 only show 3 entities of the KH100 hub.  See also #751 
I tried it for myself today again. Installed 3.1.4, restarted HA and only 3 entities in den KH100 hub are still there (firmware, signal level, overheat). I delete the integration totally and reinstalled 3.1.4, config all my Tapo devices new, same again. I downgraded to 3.0.0 and all entities in the KH100 hub are back. But only max 12 devices as mentioned in #650 
Downgrade is only possible when you download the 3.0.0 release and copy the tapo folder manually in the custom_components folder, because the 3.0.0 is not more listed in the version dropdown. For that I used the samba-add-on.
